/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Manolo
 */
public class MainContactos extends javax.swing.JFrame {

    /**
     * Creates new form MainContactos
     */
    public MainContactos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContactos = new javax.swing.JPanel();
        PanelBuscar = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        PanelLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelAgregar = new javax.swing.JPanel();
        btn_Agregar = new javax.swing.JButton();
        PanelDatos = new javax.swing.JPanel();
        PanelTag = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanelTexts = new javax.swing.JPanel();
        lbl_Nombre = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContactos.setLayout(new java.awt.BorderLayout());

        jTextField1.setText("Buscar");
        jTextField1.setMinimumSize(new java.awt.Dimension(20, 40));
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 22));
        PanelBuscar.add(jTextField1);

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });
        PanelBuscar.add(btn_Buscar);

        PanelContactos.add(PanelBuscar, java.awt.BorderLayout.PAGE_START);

        PanelLista.setLayout(new javax.swing.BoxLayout(PanelLista, javax.swing.BoxLayout.Y_AXIS));
        PanelLista.add(jScrollPane1);

        PanelContactos.add(PanelLista, java.awt.BorderLayout.CENTER);

        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });
        PanelAgregar.add(btn_Agregar);

        PanelContactos.add(PanelAgregar, java.awt.BorderLayout.SOUTH);

        getContentPane().add(PanelContactos, java.awt.BorderLayout.CENTER);

        PanelDatos.setLayout(new java.awt.BorderLayout());

        PanelTag.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("[ImageContact]");
        PanelTag.add(jLabel1, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);

        PanelTag.add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel4.setText("[Trash Icon]");
        PanelTag.add(jLabel4, java.awt.BorderLayout.EAST);

        PanelDatos.add(PanelTag, java.awt.BorderLayout.NORTH);

        PanelTexts.setLayout(new javax.swing.BoxLayout(PanelTexts, javax.swing.BoxLayout.Y_AXIS));

        lbl_Nombre.setText("Nombre");
        PanelTexts.add(lbl_Nombre);

        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });
        PanelTexts.add(txt_Nombre);

        jLabel5.setText("jLabel5");
        PanelTexts.add(jLabel5);
        PanelTexts.add(jTextField2);

        jLabel6.setText("jLabel6");
        PanelTexts.add(jLabel6);
        PanelTexts.add(jTextField3);

        jLabel7.setText("jLabel7");
        PanelTexts.add(jLabel7);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        PanelTexts.add(jScrollPane2);

        jLabel8.setText("jLabel8");
        PanelTexts.add(jLabel8);
        PanelTexts.add(jTextField4);

        jLabel9.setText("jLabel9");
        PanelTexts.add(jLabel9);
        PanelTexts.add(jDateChooser1);

        PanelDatos.add(PanelTexts, java.awt.BorderLayout.CENTER);

        jButton1.setText("Cancelar");
        jPanel2.add(jButton1);

        jButton2.setText("Aceptar");
        jPanel2.add(jButton2);

        PanelDatos.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(PanelDatos, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainContactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAgregar;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelContactos;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelLista;
    private javax.swing.JPanel PanelTag;
    private javax.swing.JPanel PanelTexts;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
